In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
concrete_data=pd.read_csv('/content/sample_data/concrete_data.csv')

In [5]:
concrete_data

Cement  Blast Furnace Slag  Fly Ash  ...  Fine Aggregate  Age  Strength
0      540.0                 0.0      0.0  ...           676.0   28     79.99
1      540.0                 0.0      0.0  ...           676.0   28     61.89
2      332.5               142.5      0.0  ...           594.0  270     40.27
3      332.5               142.5      0.0  ...           594.0  365     41.05
4      198.6               132.4      0.0  ...           825.5  360     44.30
...      ...                 ...      ...  ...             ...  ...       ...
1025   276.4               116.0     90.3  ...           768.3   28     44.28
1026   322.2                 0.0    115.6  ...           813.4   28     31.18
1027   148.5               139.4    108.6  ...           780.0   28     23.70
1028   159.1               186.7      0.0  ...           788.9   28     32.77
1029   260.9               100.5     78.3  ...           761.5   28     32.40

[1030 rows x 9 columns]

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
x=concrete_data.drop(['Strength'],axis=1)

In [8]:
x

Cement  Blast Furnace Slag  ...  Fine Aggregate  Age
0      540.0                 0.0  ...           676.0   28
1      540.0                 0.0  ...           676.0   28
2      332.5               142.5  ...           594.0  270
3      332.5               142.5  ...           594.0  365
4      198.6               132.4  ...           825.5  360
...      ...                 ...  ...             ...  ...
1025   276.4               116.0  ...           768.3   28
1026   322.2                 0.0  ...           813.4   28
1027   148.5               139.4  ...           780.0   28
1028   159.1               186.7  ...           788.9   28
1029   260.9               100.5  ...           761.5   28

[1030 rows x 8 columns]

In [10]:
y=concrete_data[['Strength']]

In [11]:
y

Strength
0        79.99
1        61.89
2        40.27
3        41.05
4        44.30
...        ...
1025     44.28
1026     31.18
1027     23.70
1028     32.77
1029     32.40

[1030 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=41)

In [20]:
x_train

Cement  Blast Furnace Slag  Fly Ash  ...  Coarse Aggregate  Fine Aggregate  Age
36    237.5               237.5      0.0  ...             932.0           594.0   28
52    237.5               237.5      0.0  ...             932.0           594.0   90
632   325.0                 0.0      0.0  ...            1063.0           783.0   28
972   145.7               172.6      0.0  ...             985.8           816.8   28
315   251.8                 0.0     99.9  ...            1006.0           899.8   14
..      ...                 ...      ...  ...               ...             ...  ...
282   251.4                 0.0    118.3  ...            1028.4           757.7   56
407   165.0               128.5    132.1  ...            1005.8           746.6    3
243   229.7                 0.0    118.2  ...            1028.1           757.6  100
321   249.1                 0.0     98.8  ...             987.8           889.0   28
931   144.0                15.0    195.0  ...            1021.0           709.0   28

[721 rows x 8 columns]

In [21]:
x_test

Cement  Blast Furnace Slag  ...  Fine Aggregate  Age
605    236.0                 0.0  ...           885.0    3
950    326.5                 0.0  ...           792.5   28
1009   298.1                 0.0  ...           815.2   28
604    339.0                 0.0  ...           781.0  365
534    393.0                 0.0  ...           785.6    3
...      ...                 ...  ...             ...  ...
181    389.9               189.0  ...           755.8   91
648    141.3               212.0  ...           748.5   28
930    159.0               209.0  ...           669.0   28
714    153.0               102.0  ...           943.1    7
281    251.4                 0.0  ...           757.7   28

[309 rows x 8 columns]

In [22]:
y_train

Strength
36      30.08
52      33.12
632     30.57
972     23.74
315     33.36
..        ...
282     36.64
407     19.42
243     40.86
321     30.85
931     15.34

[721 rows x 1 columns]

In [23]:
y_test

Strength
605       6.47
950      38.63
1009     42.64
604      38.89
534      19.20
...        ...
181      82.60
648      29.89
930      30.88
714       8.37
281      32.66

[309 rows x 1 columns]

In [16]:
x_train.shape

(721, 8)

In [17]:
x_test.shape

(309, 8)

In [18]:
y_train.shape

(721, 1)

In [19]:
y_test.shape

(309, 1)

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
mmc=MinMaxScaler()

In [26]:
x_train_mmc=mmc.fit_transform(x_train)
x_test_mmc=mmc.transform(x_test)

In [27]:
x_train_mmc

array([[0.30936073, 0.66082359, 0.        , ..., 0.38081395, 0.        ,
        0.07417582],
       [0.30936073, 0.66082359, 0.        , ..., 0.38081395, 0.        ,
        0.24450549],
       [0.50913242, 0.        , 0.        , ..., 0.76162791, 0.47415956,
        0.07417582],
       ...,
       [0.29155251, 0.        , 0.59070465, ..., 0.66017442, 0.41043653,
        0.27197802],
       [0.33584475, 0.        , 0.49375312, ..., 0.54302326, 0.74009032,
        0.07417582],
       [0.09589041, 0.04173623, 0.97451274, ..., 0.63953488, 0.28850978,
        0.07417582]])

In [28]:
x_test_mmc

array([[3.05936073e-01, 0.00000000e+00, 0.00000000e+00, ...,
        4.85465116e-01, 7.30055193e-01, 5.49450549e-03],
       [5.12557078e-01, 0.00000000e+00, 6.89155422e-01, ...,
        2.90697674e-04, 4.97992975e-01, 7.41758242e-02],
       [4.47716895e-01, 0.00000000e+00, 5.34732634e-01, ...,
        2.26744186e-01, 5.54942298e-01, 7.41758242e-02],
       ...,
       [1.30136986e-01, 5.81524763e-01, 8.04597701e-01, ...,
        1.36627907e-01, 1.88158555e-01, 7.41758242e-02],
       [1.16438356e-01, 2.83806344e-01, 0.00000000e+00, ...,
        2.52906977e-01, 8.75815354e-01, 1.64835165e-02],
       [3.41095890e-01, 0.00000000e+00, 5.91204398e-01, ...,
        6.61046512e-01, 4.10687406e-01, 7.41758242e-02]])

In [31]:
y_train_mmc=mmc.fit_transform(y_train)
y_test_mmc=mmc.transform(y_test)

In [34]:
y_train_mmc

array([[0.34940821],
       [0.38768572],
       [0.35557794],
       [0.26957945],
       [0.39070763],
       [1.        ],
       [0.44195417],
       [0.66192395],
       [0.37408713],
       [0.49534122],
       [0.32246286],
       [0.46726265],
       [0.45668597],
       [0.23167968],
       [0.39813649],
       [0.01246537],
       [0.46549987],
       [0.2260136 ],
       [0.33505414],
       [0.36665827],
       [0.63170486],
       [0.1966759 ],
       [0.74993704],
       [0.53563334],
       [0.53122639],
       [0.46361118],
       [0.27587509],
       [0.57693276],
       [0.19151347],
       [0.24112314],
       [0.15701335],
       [0.30055402],
       [0.27020902],
       [0.14945857],
       [0.62188366],
       [0.37320574],
       [0.29249559],
       [0.24729287],
       [0.51687232],
       [0.6663309 ],
       [0.52820448],
       [0.48753463],
       [0.11508436],
       [0.45177537],
       [0.48753463],
       [0.44208008],
       [0.90695039],
       [0.222

In [35]:
y_test_mmc

array([[0.05212793],
       [0.45706371],
       [0.50755477],
       [0.46033745],
       [0.21241501],
       [0.3767313 ],
       [0.37446487],
       [0.75195165],
       [0.40178796],
       [0.31024931],
       [0.48602367],
       [0.27914883],
       [0.436414  ],
       [0.33782423],
       [0.94396877],
       [0.54910602],
       [0.6800554 ],
       [0.78028204],
       [0.50478469],
       [0.5547721 ],
       [0.34991186],
       [0.97783934],
       [0.37370939],
       [0.36539914],
       [0.59733065],
       [0.46940317],
       [0.27851926],
       [0.29249559],
       [0.39498867],
       [0.68509192],
       [0.3414757 ],
       [0.55791992],
       [0.12868295],
       [0.46537396],
       [0.52216066],
       [0.0841098 ],
       [0.48602367],
       [0.16003526],
       [0.13938555],
       [0.51108033],
       [0.28405943],
       [0.63573407],
       [0.54860237],
       [0.64177789],
       [0.6437925 ],
       [0.19894233],
       [0.67753714],
       [0.106

In [36]:
x_train_mmc.shape

(721, 8)

In [37]:

import tensorflow as tf
from keras import models
from keras import layers
def build_model(act):
 model = models.Sequential()
 model.add(layers.Dense(10, activation=act,input_shape=(8,)))
 model.add(layers.Dense(5, activation=act))
 model.add(layers.Dense(1))
 model.compile(optimizer='adam', loss='mse', metrics=['mae'])
 return model


In [38]:
import numpy as np
k = 4
num_val_samples = len(x_train_mmc) // k
num_epochs = 100
all_scores= []
for i in range(k):
 print('processing fold #', i)
 val_data = x_train_mmc[i * num_val_samples: (i + 1) * num_val_samples]
 val_targets = y_train_mmc[i * num_val_samples: (i + 1) * num_val_samples]
 partial_train_data = np.concatenate([x_train_mmc[:i * num_val_samples],x_train_mmc[(i + 1) * num_val_samples:]],axis=0)
 partial_train_targets = np.concatenate([y_train_mmc[:i * num_val_samples],y_train_mmc[(i + 1) * num_val_samples:]],axis=0)
 model = build_model('relu')
 model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
 val_mse, val_mae = model.evaluate(val_data, val_targets, verbose=0)
 all_scores.append(val_mae)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3


In [39]:
all_scores

[0.06508024781942368,
 0.06232624500989914,
 0.06244185194373131,
 0.0679963082075119]

In [40]:
np.mean(all_scores)

0.0644611632451415

In [41]:
model_relu=build_model('relu')

In [42]:
model_relu.fit(x_train_mmc,y_train_mmc,epochs=100,batch_size=1)

Epoch 1/100
721/721 [==============================] - 1s 878us/step - loss: 0.0562 - mae: 0.1950
Epoch 2/100
721/721 [==============================] - 1s 909us/step - loss: 0.0245 - mae: 0.1272
Epoch 3/100
721/721 [==============================] - 1s 871us/step - loss: 0.0183 - mae: 0.1103
Epoch 4/100
721/721 [==============================] - 1s 887us/step - loss: 0.0158 - mae: 0.0992
Epoch 5/100
721/721 [==============================] - 1s 887us/step - loss: 0.0157 - mae: 0.0972
Epoch 6/100
721/721 [==============================] - 1s 896us/step - loss: 0.0134 - mae: 0.0904
Epoch 7/100
721/721 [==============================] - 1s 868us/step - loss: 0.0135 - mae: 0.0887
Epoch 8/100
721/721 [==============================] - 1s 916us/step - loss: 0.0111 - mae: 0.0821
Epoch 9/100
721/721 [==============================] - 1s 889us/step - loss: 0.0108 - mae: 0.0795
Epoch 10/100
721/721 [==============================] - 1s 869us/step - loss: 0.0101 - mae: 0.0765
Epoch 11/100
721/72

In [43]:
loss,mae=model_relu.evaluate(x_test_mmc,y_test_mmc)

10/10 [==============================] - 0s 1ms/step - loss: 0.0062 - mae: 0.0583


In [44]:
loss

0.00620189169421792

In [45]:
mae

0.058293893933296204

In [46]:
y_pred=model_relu.predict(x_test)

In [47]:
y_pred

array([[176.21687],
       [423.43597],
       [360.55597],
       [374.88855],
       [268.18365],
       [326.32553],
       [307.73993],
       [575.8724 ],
       [315.48303],
       [299.90512],
       [306.6488 ],
       [266.2232 ],
       [365.53305],
       [300.59015],
       [427.5428 ],
       [415.32614],
       [486.01422],
       [446.14664],
       [364.5043 ],
       [360.09842],
       [381.13583],
       [444.01352],
       [477.36557],
       [326.37213],
       [347.55817],
       [387.53342],
       [269.4639 ],
       [338.77335],
       [341.82538],
       [452.85617],
       [352.0571 ],
       [468.30542],
       [257.49417],
       [368.75433],
       [414.90506],
       [257.0877 ],
       [332.016  ],
       [259.0309 ],
       [340.32614],
       [363.84915],
       [303.24396],
       [397.99847],
       [377.44644],
       [379.3606 ],
       [446.98962],
       [250.73373],
       [560.61957],
       [291.71817],
       [320.35324],
       [416.56485],
