In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
import numpy as np

In [2]:
import pandas as pd

In [9]:
credit_card_df=pd.read_csv('/content/sample_data/creditcard.csv')

In [10]:
credit_card_df

Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284807 rows x 31 columns]

In [11]:
credit_card_df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [15]:
credit_card_df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [16]:
non_fraud=credit_card_df[credit_card_df['Class']==0]
fraud=credit_card_df[credit_card_df['Class']==1]

In [17]:
non_fraud.shape

(284315, 31)

In [19]:
fraud.shape

(492, 31)

In [20]:
non_fraud=non_fraud.sample(fraud.shape[0])

In [21]:
non_fraud.shape

(492, 31)

In [22]:
data=fraud.append(non_fraud,ignore_index=True)

In [23]:
data

Time        V1        V2        V3  ...       V27       V28  Amount  Class
0       406.0 -2.312227  1.951992 -1.609851  ...  0.261145 -0.143276    0.00      1
1       472.0 -3.043541 -3.157307  1.088463  ... -0.252773  0.035764  529.00      1
2      4462.0 -2.303350  1.759247 -0.359745  ...  0.039566 -0.153029  239.93      1
3      6986.0 -4.397974  1.358367 -2.592844  ... -0.827136  0.849573   59.00      1
4      7519.0  1.234235  3.019740 -4.304597  ... -0.010016  0.146793    1.00      1
..        ...       ...       ...       ...  ...       ...       ...     ...    ...
979   65261.0  1.039585 -1.331861  1.092107  ...  0.012847  0.052408  162.00      0
980   39319.0 -5.754610 -3.212647 -0.994316  ...  0.440104  0.974880   89.99      0
981   60997.0  1.169812  0.229150  0.289911  ... -0.012751  0.016481    1.98      0
982  139598.0 -4.255515  2.631714 -1.496336  ...  0.666785  0.606528   49.48      0
983  135829.0  1.043831  0.779673 -1.695555  ...  0.241432  0.118764  120.40      0

[984 rows x 31 columns]

In [24]:
data['Class'].value_counts()

1    492
0    492
Name: Class, dtype: int64

In [25]:
x=data.drop(['Class'],axis=1)

In [26]:
x

Time        V1        V2  ...       V27       V28  Amount
0       406.0 -2.312227  1.951992  ...  0.261145 -0.143276    0.00
1       472.0 -3.043541 -3.157307  ... -0.252773  0.035764  529.00
2      4462.0 -2.303350  1.759247  ...  0.039566 -0.153029  239.93
3      6986.0 -4.397974  1.358367  ... -0.827136  0.849573   59.00
4      7519.0  1.234235  3.019740  ... -0.010016  0.146793    1.00
..        ...       ...       ...  ...       ...       ...     ...
979   65261.0  1.039585 -1.331861  ...  0.012847  0.052408  162.00
980   39319.0 -5.754610 -3.212647  ...  0.440104  0.974880   89.99
981   60997.0  1.169812  0.229150  ... -0.012751  0.016481    1.98
982  139598.0 -4.255515  2.631714  ...  0.666785  0.606528   49.48
983  135829.0  1.043831  0.779673  ...  0.241432  0.118764  120.40

[984 rows x 30 columns]

In [27]:
y=data[['Class']]

In [28]:
y

Class
0        1
1        1
2        1
3        1
4        1
..     ...
979      0
980      0
981      0
982      0
983      0

[984 rows x 1 columns]

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=40)

In [31]:
x_train

Time         V1        V2  ...       V27       V28  Amount
129   41353.0 -15.020981  8.075240  ... -1.310888 -0.707403   34.12
363  123525.0  -5.904921  4.439911  ... -1.167566 -1.206354   45.51
792  147686.0  -0.514516 -0.728684  ... -0.023985  0.157872  405.00
186   56806.0   0.016828  2.400826  ...  0.874494  0.470434    1.00
579  152893.0   2.064032  0.178327  ... -0.005747 -0.033170    2.00
..        ...        ...       ...  ...       ...       ...     ...
440  151916.0  -5.488032  3.329561  ... -1.937473  1.521218    0.01
165   50808.0  -9.169790  7.092197  ...  1.159690  0.232758   99.99
7      7543.0   0.329594  3.712889  ...  0.530507  0.404474    1.00
219   65728.0   1.227614 -0.668974  ... -0.001128  0.035075   98.01
326   96291.0  -3.552173  5.426461  ...  0.023025  0.164741   33.59

[688 rows x 30 columns]

In [32]:
x_test

Time         V1         V2  ...       V27       V28  Amount
275   85285.0  -6.713407   3.921104  ...  1.649906 -0.394905  252.92
239   72327.0  -4.198735   0.194121  ...  1.249414 -0.131525  238.90
652  131883.0   1.958378  -0.428423  ... -0.012095 -0.043509   23.00
71    27219.0 -25.266355  14.323254  ...  1.411855  0.414656   99.99
42    17520.0  -5.268053   9.067613  ...  1.584697  0.720056    1.00
..        ...        ...        ...  ...       ...       ...     ...
712   81868.0   1.217008  -0.465946  ... -0.042915  0.012741   34.95
53    21046.0 -16.917468   9.669900  ...  2.108471 -1.421243    1.00
154   46149.0  -1.346509   2.132431  ...  0.395451  0.233139    1.00
487  169142.0  -1.927883   1.125653  ...  0.292680  0.147968  390.00
383  132688.0   0.432554   1.861373  ...  0.387039  0.319402    1.00

[296 rows x 30 columns]

In [34]:
y_train

Class
129      1
363      1
792      0
186      1
579      0
..     ...
440      1
165      1
7        1
219      1
326      1

[688 rows x 1 columns]

In [35]:
y_test

Class
275      1
239      1
652      0
71       1
42       1
..     ...
712      0
53       1
154      1
487      1
383      1

[296 rows x 1 columns]

In [36]:
x_train.shape

(688, 30)

In [37]:
x_test.shape

(296, 30)

In [39]:
y_train.shape

(688, 1)

In [40]:
y_test.shape

(296, 1)

In [41]:
from sklearn.preprocessing import MinMaxScaler

In [42]:
mmc=MinMaxScaler()

In [43]:
x_train_mmc=mmc.fit_transform(x_train)
x_test_mmc=mmc.transform(x_test)

In [44]:
x_train_mmc

array([[2.30075091e-01, 4.73566075e-01, 6.23685315e-01, ...,
        5.77034407e-01, 3.11018167e-01, 1.41912997e-02],
       [7.12511816e-01, 7.51522782e-01, 4.65314885e-01, ...,
        5.90927780e-01, 1.56766570e-01, 1.89286650e-02],
       [8.54362491e-01, 9.15880968e-01, 2.40148789e-01, ...,
        7.01784559e-01, 5.78519450e-01, 1.68448898e-01],
       ...,
       [3.15745595e-02, 9.41618650e-01, 4.33642698e-01, ...,
        7.55536114e-01, 6.54756721e-01, 4.15923204e-04],
       [3.73182173e-01, 9.69000075e-01, 2.42750027e-01, ...,
        7.04000254e-01, 5.40556263e-01, 4.07646332e-02],
       [5.52619373e-01, 8.23260144e-01, 5.08293180e-01, ...,
        7.06341648e-01, 5.80642745e-01, 1.39708604e-02]])

In [45]:
x_test_mmc

array([[4.88002489e-01, 7.26871326e-01, 4.42713427e-01, ...,
        8.64048706e-01, 4.07627302e-01, 1.05195297e-01],
       [4.11925297e-01, 8.03545905e-01, 2.80350107e-01, ...,
        8.25225668e-01, 4.89051872e-01, 9.93640534e-02],
       [7.61582133e-01, 9.91281695e-01, 2.53229436e-01, ...,
        7.02937152e-01, 5.16261913e-01, 9.56623369e-03],
       ...,
       [2.58232694e-01, 8.90512786e-01, 3.64791169e-01, ...,
        7.42443981e-01, 6.01788086e-01, 4.15923204e-04],
       [9.80331950e-01, 8.72786165e-01, 3.20931621e-01, ...,
        7.32481527e-01, 5.75457445e-01, 1.62210050e-01],
       [7.66308336e-01, 9.44757996e-01, 3.52982756e-01, ...,
        7.41628523e-01, 6.28456416e-01, 4.15923204e-04]])

In [46]:
y_train=y_train.to_numpy()

In [47]:
y_train

array([[1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
    

In [48]:
y_test=y_test.to_numpy()

In [49]:
y_test

array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
    

In [50]:
x_train_mmc.shape

(688, 30)

In [51]:

import tensorflow as tf
from keras import models
from keras import layers
def build_model(act):
 model = models.Sequential()
 model.add(layers.Dense(16, activation=act,input_shape=(30,)))
 model.add(layers.Dense(8, activation=act))
 model.add(layers.Dense(1, activation='sigmoid'))
 model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
 return model


In [52]:
import numpy as np
k = 4
num_val_samples = len(x_train_mmc) // k
num_epochs = 100
all_scores= []
for i in range(k):
 print('processing fold #', i)
 val_data = x_train_mmc[i * num_val_samples: (i + 1) * num_val_samples]
 val_targets = y_train[i * num_val_samples: (i + 1) * num_val_samples]
 partial_train_data = np.concatenate([x_train_mmc[:i * num_val_samples],x_train_mmc[(i + 1) * num_val_samples:]],axis=0)
 partial_train_targets = np.concatenate([y_train[:i * num_val_samples],y_train[(i + 1) * num_val_samples:]],axis=0)
 model = build_model('relu')
 model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
 val_mse, val_accuracy = model.evaluate(val_data, val_targets, verbose=0)
 all_scores.append(val_accuracy)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3


In [53]:
all_scores

[0.930232584476471, 0.895348846912384, 0.9418604373931885, 0.9476743936538696]

In [54]:
np.mean(all_scores)

0.9287790656089783

In [55]:
model_relu=build_model('relu')

In [56]:
model_relu.fit(x_train_mmc,y_train,epochs=100,batch_size=1)

Epoch 1/100
688/688 [==============================] - 1s 1ms/step - loss: 0.6068 - accuracy: 0.7000
Epoch 2/100
688/688 [==============================] - 1s 1ms/step - loss: 0.3567 - accuracy: 0.8687
Epoch 3/100
688/688 [==============================] - 1s 1ms/step - loss: 0.2700 - accuracy: 0.9001
Epoch 4/100
688/688 [==============================] - 1s 1ms/step - loss: 0.2259 - accuracy: 0.9166
Epoch 5/100
688/688 [==============================] - 1s 1ms/step - loss: 0.2087 - accuracy: 0.9235
Epoch 6/100
688/688 [==============================] - 1s 1ms/step - loss: 0.2135 - accuracy: 0.9157
Epoch 7/100
688/688 [==============================] - 1s 1ms/step - loss: 0.2285 - accuracy: 0.8923
Epoch 8/100
688/688 [==============================] - 1s 1ms/step - loss: 0.2084 - accuracy: 0.9321
Epoch 9/100
688/688 [==============================] - 1s 1ms/step - loss: 0.2395 - accuracy: 0.9022
Epoch 10/100
688/688 [==============================] - 1s 1ms/step - loss: 0.1545 - accura

In [57]:
loss,accuracy=model_relu.evaluate(x_test_mmc,y_test)

10/10 [==============================] - 0s 1ms/step - loss: 0.1449 - accuracy: 0.9426


In [58]:
loss

0.14492830634117126

In [59]:
accuracy

0.9425675868988037

In [60]:
y_pred=model_relu.predict(x_test_mmc)

In [61]:
y_pred

array([[1.        ],
       [0.9999789 ],
       [0.0091908 ],
       [1.        ],
       [1.        ],
       [0.986951  ],
       [0.9999765 ],
       [0.12899733],
       [0.9905561 ],
       [0.00742665],
       [0.96969306],
       [0.9885149 ],
       [0.16042352],
       [0.22654566],
       [0.00606412],
       [0.0332239 ],
       [0.04175961],
       [0.01048169],
       [0.48246914],
       [0.0344159 ],
       [0.2806573 ],
       [0.02529657],
       [1.        ],
       [0.98942244],
       [0.99886435],
       [0.04380128],
       [0.01254275],
       [0.02093905],
       [0.01601902],
       [0.99999964],
       [0.0066171 ],
       [0.04407212],
       [0.9999537 ],
       [0.999967  ],
       [0.9999997 ],
       [0.9687735 ],
       [0.04735401],
       [0.1579102 ],
       [0.04496482],
       [1.        ],
       [0.00382242],
       [0.99904823],
       [1.        ],
       [0.9999788 ],
       [0.03780645],
       [0.17912877],
       [0.9999993 ],
       [0.017