In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
ionosphere_df=pd.read_csv('/content/sample_data/ionosphere_data_kaggle.csv')

In [5]:
ionosphere_df

feature1  feature2  feature3  ...  feature33  feature34  label
0           1         0   0.99539  ...    0.18641   -0.45300      g
1           1         0   1.00000  ...   -0.13738   -0.02447      b
2           1         0   1.00000  ...    0.56045   -0.38238      g
3           1         0   1.00000  ...   -0.32382    1.00000      b
4           1         0   1.00000  ...   -0.04608   -0.65697      g
..        ...       ...       ...  ...        ...        ...    ...
346         1         0   0.83508  ...    0.90546   -0.04307      g
347         1         0   0.95113  ...    0.91483    0.04712      g
348         1         0   0.94701  ...    0.92697   -0.00577      g
349         1         0   0.90608  ...    0.87403   -0.16243      g
350         1         0   0.84710  ...    0.85764   -0.06151      g

[351 rows x 35 columns]

In [6]:
ionosphere_df.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [10]:
df1=ionosphere_df[['label']]

In [11]:
df1

label
0       g
1       b
2       g
3       b
4       g
..    ...
346     g
347     g
348     g
349     g
350     g

[351 rows x 1 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le=LabelEncoder()

In [14]:
df1_label=le.fit_transform(df1)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [15]:
df1_label

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [16]:
df1_df=pd.DataFrame(df1_label,columns=['label'])

In [17]:
df1_df

label
0        1
1        0
2        1
3        0
4        1
..     ...
346      1
347      1
348      1
349      1
350      1

[351 rows x 1 columns]

In [18]:
df2=ionosphere_df.drop(['label'],axis=1)

In [19]:
df2

feature1  feature2  feature3  ...  feature32  feature33  feature34
0           1         0   0.99539  ...   -0.54487    0.18641   -0.45300
1           1         0   1.00000  ...   -0.06288   -0.13738   -0.02447
2           1         0   1.00000  ...   -0.24180    0.56045   -0.38238
3           1         0   1.00000  ...    1.00000   -0.32382    1.00000
4           1         0   1.00000  ...   -0.59573   -0.04608   -0.65697
..        ...       ...       ...  ...        ...        ...        ...
346         1         0   0.83508  ...   -0.10714    0.90546   -0.04307
347         1         0   0.95113  ...   -0.00035    0.91483    0.04712
348         1         0   0.94701  ...    0.00442    0.92697   -0.00577
349         1         0   0.90608  ...   -0.03757    0.87403   -0.16243
350         1         0   0.84710  ...   -0.06678    0.85764   -0.06151

[351 rows x 34 columns]

In [22]:
final_df=pd.concat([df2,df1_df],axis=1)

In [23]:
final_df

feature1  feature2  feature3  ...  feature33  feature34  label
0           1         0   0.99539  ...    0.18641   -0.45300      1
1           1         0   1.00000  ...   -0.13738   -0.02447      0
2           1         0   1.00000  ...    0.56045   -0.38238      1
3           1         0   1.00000  ...   -0.32382    1.00000      0
4           1         0   1.00000  ...   -0.04608   -0.65697      1
..        ...       ...       ...  ...        ...        ...    ...
346         1         0   0.83508  ...    0.90546   -0.04307      1
347         1         0   0.95113  ...    0.91483    0.04712      1
348         1         0   0.94701  ...    0.92697   -0.00577      1
349         1         0   0.90608  ...    0.87403   -0.16243      1
350         1         0   0.84710  ...    0.85764   -0.06151      1

[351 rows x 35 columns]

In [24]:
final_df.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [27]:
x=final_df.drop(['label'],axis=1)

In [28]:
x

feature1  feature2  feature3  ...  feature32  feature33  feature34
0           1         0   0.99539  ...   -0.54487    0.18641   -0.45300
1           1         0   1.00000  ...   -0.06288   -0.13738   -0.02447
2           1         0   1.00000  ...   -0.24180    0.56045   -0.38238
3           1         0   1.00000  ...    1.00000   -0.32382    1.00000
4           1         0   1.00000  ...   -0.59573   -0.04608   -0.65697
..        ...       ...       ...  ...        ...        ...        ...
346         1         0   0.83508  ...   -0.10714    0.90546   -0.04307
347         1         0   0.95113  ...   -0.00035    0.91483    0.04712
348         1         0   0.94701  ...    0.00442    0.92697   -0.00577
349         1         0   0.90608  ...   -0.03757    0.87403   -0.16243
350         1         0   0.84710  ...   -0.06678    0.85764   -0.06151

[351 rows x 34 columns]

In [29]:
y=final_df[['label']]

In [30]:
y

label
0        1
1        0
2        1
3        0
4        1
..     ...
346      1
347      1
348      1
349      1
350      1

[351 rows x 1 columns]

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.3, random_state=45)

In [33]:
x_train.shape

(245, 34)

In [34]:
x_test.shape

(106, 34)

In [35]:
y_train.shape

(245, 1)

In [36]:
y_test.shape

(106, 1)

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
mmc=MinMaxScaler()

In [39]:
x_train_mmc=mmc.fit_transform(x_train)
x_test_mmc=mmc.transform(x_test)

In [40]:
x_train_mmc

array([[1.      , 0.      , 1.      , ..., 0.      , 0.5     , 0.5     ],
       [1.      , 0.      , 0.917135, ..., 0.850055, 0.480085, 0.89722 ],
       [1.      , 0.      , 1.      , ..., 0.444445, 1.      , 0.5     ],
       ...,
       [1.      , 0.      , 0.895785, ..., 0.5643  , 0.5     , 0.5     ],
       [1.      , 0.      , 0.94104 , ..., 0.213115, 0.710945, 0.20957 ],
       [1.      , 0.      , 0.82061 , ..., 0.5     , 0.585365, 0.536585]])

In [41]:
x_test_mmc

array([[1.      , 0.      , 0.93142 , ..., 0.400385, 0.28544 , 0.34023 ],
       [1.      , 0.      , 1.      , ..., 0.32657 , 1.      , 0.674225],
       [1.      , 0.      , 0.87352 , ..., 0.534585, 0.805335, 0.493085],
       ...,
       [1.      , 0.      , 0.93886 , ..., 0.44565 , 0.89538 , 0.497285],
       [1.      , 0.      , 0.84099 , ..., 0.53532 , 0.479935, 0.52293 ],
       [1.      , 0.      , 0.692605, ..., 0.65564 , 0.40467 , 0.64397 ]])

In [42]:
y_train=y_train.to_numpy()

In [43]:
y_train

array([[0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
    

In [44]:
y_test=y_test.to_numpy()

In [45]:
y_test

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
    

In [49]:

import tensorflow as tf
from keras import models
from keras import layers
def build_model(act):
 model = models.Sequential()
 model.add(layers.Dense(18, activation=act,input_shape=(34,)))
 model.add(layers.Dense(10, activation=act))
 model.add(layers.Dense(1, activation='sigmoid'))
 model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
 return model


In [50]:
import numpy as np
k = 4
num_val_samples = len(x_train_mmc) // k
num_epochs = 100
all_scores= []
for i in range(k):
 print('processing fold #', i)
 val_data = x_train_mmc[i * num_val_samples: (i + 1) * num_val_samples]
 val_targets = y_train[i * num_val_samples: (i + 1) * num_val_samples]
 partial_train_data = np.concatenate([x_train_mmc[:i * num_val_samples],x_train_mmc[(i + 1) * num_val_samples:]],axis=0)
 partial_train_targets = np.concatenate([y_train[:i * num_val_samples],y_train[(i + 1) * num_val_samples:]],axis=0)
 model = build_model('relu')
 model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=0)
 val_mse, val_accuracy = model.evaluate(val_data, val_targets, verbose=0)
 all_scores.append(val_accuracy)

processing fold # 0
processing fold # 1
processing fold # 2
processing fold # 3


In [51]:
all_scores

[0.9344262480735779,
 0.9672130942344666,
 0.9344262480735779,
 0.8524590134620667]

In [52]:
np.mean(all_scores)

0.9221311509609222

In [53]:
model_relu=build_model('relu')

In [54]:
model_relu.fit(x_train_mmc,y_train,epochs=100,batch_size=1)

Epoch 1/100
245/245 [==============================] - 1s 1ms/step - loss: 0.6095 - accuracy: 0.7269
Epoch 2/100
245/245 [==============================] - 0s 1ms/step - loss: 0.5648 - accuracy: 0.6878
Epoch 3/100
245/245 [==============================] - 0s 1ms/step - loss: 0.5166 - accuracy: 0.7245
Epoch 4/100
245/245 [==============================] - 0s 1ms/step - loss: 0.4858 - accuracy: 0.7760
Epoch 5/100
245/245 [==============================] - 0s 1ms/step - loss: 0.4226 - accuracy: 0.7964
Epoch 6/100
245/245 [==============================] - 0s 1ms/step - loss: 0.4118 - accuracy: 0.8820
Epoch 7/100
245/245 [==============================] - 0s 1ms/step - loss: 0.3250 - accuracy: 0.8788
Epoch 8/100
245/245 [==============================] - 0s 1ms/step - loss: 0.3642 - accuracy: 0.8373
Epoch 9/100
245/245 [==============================] - 0s 1ms/step - loss: 0.3388 - accuracy: 0.8751
Epoch 10/100
245/245 [==============================] - 0s 1ms/step - loss: 0.2930 - accura

In [55]:
loss,accuracy=model_relu.evaluate(x_test_mmc,y_test)

4/4 [==============================] - 0s 5ms/step - loss: 0.3998 - accuracy: 0.9245


In [56]:
loss

0.3997753858566284

In [57]:
accuracy

0.9245283007621765

In [59]:
y_pred=model_relu.predict(x_test_mmc)

In [60]:
y_pred

array([[9.99991894e-01],
       [1.00000000e+00],
       [9.96724308e-01],
       [9.99958038e-01],
       [9.99558687e-01],
       [9.99892712e-01],
       [9.99991000e-01],
       [2.17795372e-04],
       [9.99860764e-01],
       [5.33238875e-08],
       [1.71845257e-02],
       [9.94336963e-01],
       [9.99998689e-01],
       [9.99998510e-01],
       [9.99973059e-01],
       [1.06390369e-04],
       [8.89342308e-01],
       [9.99982595e-01],
       [4.37297331e-07],
       [9.99999583e-01],
       [9.99992073e-01],
       [9.99738455e-01],
       [9.99986649e-01],
       [9.99956250e-01],
       [9.85340476e-01],
       [8.86275245e-07],
       [7.49267102e-08],
       [1.58668649e-06],
       [9.99822736e-01],
       [4.01395445e-10],
       [9.98533428e-01],
       [2.72098184e-03],
       [9.99978304e-01],
       [9.99806166e-01],
       [3.28747690e-01],
       [9.95524168e-01],
       [9.99857247e-01],
       [2.18949020e-02],
       [9.99957919e-01],
       [9.99876618e-01],
